name: example
description: Example for fl_chart
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  fl_chart:
    path: ../
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.5

dev_dependencies:
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  fonts:
    - family: Digital
      fonts:
        - asset: assets/digital-7.ttf
  assets:
    - assets/
