name: example
description: Example of fl_chart
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart:
    path: ../
  flutter_svg: ^1.1.5

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Digital
      fonts:
        - asset: assets/digital-7.ttf
  assets:
    - assets/
