name: fl_chart_app
description: FL Chart App is an application to demonstrate samples of the fl_chart (A Flutter package to draw charts).
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.5
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.6
  universal_platform: ^1.0.0+1
  flutter_staggered_grid_view: ^0.6.2
  url_launcher: ^6.1.8
  go_router: ^6.0.1
  dartx: ^1.1.0
  fl_chart:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Digital
      fonts:
        - asset: assets/fonts/digital-7.ttf

  assets:
    - assets/icons/
    - assets/fonts/