name: example_new
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.6
  universal_platform: ^1.0.0+1
  flutter_staggered_grid_view: ^0.6.2
  fl_chart:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Digital
      fonts:
        - asset: assets/fonts/digital-7.ttf

  assets:
    - assets/icons/
    - assets/fonts/