include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - "**.mocks.dart"
linter:
  rules:
    avoid_bool_literals_in_conditional_expressions: false
    avoid_dynamic_calls: false
    avoid_multiple_declarations_per_line: false
    avoid_positional_boolean_parameters: false
    cast_nullable_to_non_nullable: false
    comment_references: false
    flutter_style_todos: false
    library_private_types_in_public_api: false
    lines_longer_than_80_chars: false
    no_default_cases: false
    noop_primitive_operations: false
    parameter_assignments: false
    prefer_asserts_with_message: false
    prefer_constructors_over_static_methods: false
    public_member_api_docs: false
    use_if_null_to_convert_nulls_to_bools: false
    use_setters_to_change_properties: false
