name: fl_chart
description: Draw Flutter Charts
version: 0.0.1
author: Iman Khoshabi <iman.neofight@gmail.com>
homepage: https://github.com/imaNNeoFighT/fl_chart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter