name: fl_chart
description: A powerful Flutter chart library, currently supporting Line Chart, Bar Chart and Pie Chart.
version: 0.55.2
homepage: https://github.com/imaNNeoFighT/fl_chart

environment:
  sdk: ">=2.12.0 <3.0.0"

funding:
  - https://www.buymeacoffee.com/fl_chart

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  mockito: ^5.3.0
  vector_math: ^2.1.2 #Added to use in some generated codes of mockito
  very_good_analysis: ^3.1.0


