name: fl_chart
description: A powerful Flutter chart library, currently supporting Line Chart, Bar Chart and Pie Chart.
version: 0.36.4
homepage: https://github.com/imaNNeoFighT/fl_chart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.0
  pedantic: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter


