name: Code Verification

on: [ push, pull_request ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Get packages
        run: flutter pub get
      - name: Check formattting
        run: make checkFormat
      - name: Analyze the source code
        run: make analyze
      - name: Run tests
        run: make test